### ISSUE TITLE
Process Audio Command to Text

### ISSUE THREAD

**Issue by erolley-parnell** [LiamWellacott/CDT2019-ERL#22]
(Please Edit as Necessary)
Using the stereo microphones or an Amazon Alexa, record the spoken instructions and record as text.

**Comment by emnault** [comment]
> (Please Edit as Necessary)
> Using the stereo microphones or an Amazon Alexa, record the spoken instructions and record as text.

Just for future reference, the rules state we cannot add additional sensors to the robot, so in the end we'll need to use the microphones on the Tiago.
